aws/amazon-ecs-cni-plugins

plugins/eni/version/cnispec/spec.go, plugins/ipam/README.md, plugins/ipam/commands/commands.go, plugins/ipam/config/config.go, plugins/ipam/ipstore/ipstore.go
Fix #22 and #5 issue, where ipam plugin will store the id passed in as the value instead of the  timestamps, also added the function that ipam can release the ip address by this id.
Manually tested with both setup and cleanup as in this PR: aws/amazon-ecs-agent/#779
=> Change the value of ipam key-value pair to id that can be more useful instead of timestamps

Makefile
Should fix #38 
```bash
$ make clean plugins
rm -rf /local/home/aithal/workspace/src/github.com/aws/amazon-ecs-cni-plugins/bin ||:
GOOS=linux CGO_ENABLED=0 go build -installsuffix cgo -a -ldflags "\
-X github.com/aws/amazon-ecs-cni-plugins/pkg/version.GitShortHash=5fc1911 \
-X github.com/aws/amazon-ecs-cni-plugins/pkg/version.GitPorcelain=0 \
-X github.com/aws/amazon-ecs-cni-plugins/pkg/version.Version=0.1.0 -s" \
-o /local/home/aithal/workspace/src/github.com/aws/amazon-ecs-cni-plugins/bin/plugins/ecs-eni github.com/aws/amazon-ecs-cni-plugins/plugins/eni
Built eni plugin
GOOS=linux CGO_ENABLED=0 go build -installsuffix cgo -a -ldflags "\
-X github.com/aws/amazon-ecs-cni-plugins/pkg/version.GitShortHash=5fc1911 \
-X github.com/aws/amazon-ecs-cni-plugins/pkg/version.GitPorcelain=0 \
-X …
```
=> Makefile: add ecs- prefix for eni and ipam plugins.

plugins/eni/commands/commands.go, plugins/ipam/commands/commands.go
Doing this in main doesn't capture the  logs that are emitted in add and delete commands.
=> flush logs in add and delete commands.

plugins/ecs-bridge/commands/commands.go, plugins/ecs-bridge/main.go, plugins/eni/main.go, plugins/ipam/config/config.go, plugins/ipam/main.go
The agent mount` /var/lib/ecs/data` as `/data`, change the default ipam path to `/data/ipam` so that it will persistent in `/var/lib/ecs/data` on the host.
Also the `/var/log/ecs` was mounted as `/log` inside agent.
=> Fixing the bridge return result and the path of log file and ipam store

plugins/eni/README.md, plugins/eni/commands/commands.go, plugins/eni/commands/commands_test.go, plugins/eni/e2eTests/e2e_test.go, plugins/eni/engine/engine.go, plugins/eni/engine/engine_test.go, plugins/eni/engine/mocks/engine_mocks.go, plugins/eni/engine/nsclosure.go, plugins/eni/types/types.go, scripts/mockgen.go
ENI plugin adds a `blackhole` route to `169.254.169.254` if `block-instance-metadata` config  parameter is set to `true`
From [README](https://github.com/aaithal/amazon-ecs-cni-plugins-1/blob/06af3daac1437a016e62ca959cb31a3acce81014/plugins/eni/README.md):
```
{
"type":"ecs-eni",
"cniVersion":"0.3.0",
"eni":"eni-eni01en1",
"ipv4-address":"172.31.31.65/20",
"mac":"01:23:45:67:89:ab",
"block-instance-metadata":true
}
```
Verified that new updated tests pass:
```
$ ip netns exec 314e45c385dd ip route
default via xxx dev eth1
...
blackhole 169.254.169.254
169.254.170.2 via 169.254.172.1 dev ecs-eth0
$ ip netns exec 314e45c385dd curl 169.254.169.254
curl: (7) Couldn't connect to server
```
=> Add a parameter in ENI plugin to block Instance Metadata Service access

plugins/eni/engine/dhclient.go, plugins/eni/engine/dhclient_test.go, plugins/eni/engine/engine.go, plugins/eni/engine/engine_test.go, plugins/eni/engine/nsclosure.go
Benchmarking experiments show that there's usually 3-6s delay in
IPv6 address path being populated in Instance Metadata for ENI.
We also need to take into account delays in cleaning up of the
dhclient processes running in the default network namespace.
This commit adds retries for both of these to account for these
delays. This will result in a latency increase in surfacing errors
when there are failures such as wrong MAC Address being specified
in the CNI config. However, we err on the side of correctness,
fault tolerance and caution, and deem that as an acceptable cost.
```
$ make clean plugins unit-test integration-test e2e-test; echo $?
0
```
=> IPv6 fixes

pkg/utils/utils.go, pkg/utils/utils_test.go, plugins/ecs-bridge/commands/commands.go, plugins/ipam/config/config.go
This PR will suppress the error caused by calling the bridge plugin without specifying the `ipam` plugin. This kind of behavior happens in ecs-agent: aws/amazon-ecs-agent#976
=> Skip IPAM del when IPAM isn't specified in the configuration

plugins/eni/commands/commands.go, plugins/eni/engine/engine.go, plugins/eni/engine/engine_test.go, plugins/eni/engine/nsclosure.go
Since the default ipv6 gateway can also be configured based on the
ipv6 address when the address is assigned, we sometimes get the
"file exists" error when adding the default route for the ipv6
gateway. This change ignores that error.
There are also logging improvements to log either the eni id or the
device name in various log messages for the eni plugin.
```
$ make clean plugins unit-test integration-test e2e-test; echo $?
0
```
=> eni: ignore 'file exists' for default ipv6 route

pkg/utils/backoff.go, pkg/utils/backoff_test.go, pkg/utils/errors.go, pkg/utils/utils.go, pkg/utils/utils_test.go, plugins/eni/commands/commands.go, plugins/eni/commands/commands_test.go, plugins/eni/engine/dhclient_test.go, plugins/eni/engine/engine.go, plugins/eni/engine/engine_test.go, plugins/eni/engine/error.go
This PR adds backoff retry logic for retrieving mac address of the eni from ec2 instance metadata.
=> Adding retry for eni plugin to acquire mac address

plugins/eni/commands/commands.go
5 seconds seems too low for eni information to be available in ec2 instance metadata. Sometimes this could be as long as 18 seconds. Increase this to 30 seconds for safe.
=> Increase the timeout for ec2 instance metadata

plugins/ecs-bridge/e2eTests/e2e_test.go, plugins/ecs-bridge/engine/configureveth.go, plugins/ecs-bridge/engine/engine_test.go
This PR is trying to fix issue: aws/amazon-ecs-agent#1230 by adding a route for the arp query from host,
After adding this, the route inside the container will look like:
```
root@797087bca637:/# ip route
default via 172.31.192.1 dev eth0
169.254.170.2 via 169.254.172.1 dev ecs-eth0
169.254.172.1 via 169.254.172.1 dev ecs-eth0
172.31.192.0/20 dev eth0  proto kernel  scope link  src 172.31.198.99
```
The issue can be reproduced without this change but not with this change  by the following steps:
* inside container: curl 169.254.170.2/v2/metadata
* inside container: arp -a
* host: sudo arp -d 169.254.172.2
* inside container: curl  --connection-timeout 5 169.254.170.2/v2/metadata  (this will timeout without the change)
=> Add a route for arp query request from host

Makefile
Use 8 character short sha in the Makefile.
This change was suggested in https://github.com/aws/amazon-ecs-agent/pull/1287
This contribution is under the terms of the Apache 2.0 License: yes
=> Use 8 character git short sha

CHANGELOG.md, pkg/utils/gateway.go, pkg/utils/gateway_test.go, plugins/eni/README.md, plugins/eni/commands/commands.go, plugins/eni/commands/commands_test.go, plugins/eni/e2eTests/e2e_test.go, plugins/eni/engine/engine.go, plugins/eni/engine/engine_test.go, plugins/eni/engine/error.go, plugins/eni/types/types.go
Add functionality to parse ipv4 subnet gateway from config. This eliminates the dependency on instance metadata service for the ENI plugin, which should hopefully reduce the ENI setup time.
Added a new config field for supplying ipv4 subnet gateway address for
the caller. When that's specified the plugin can use that directly
instead of looking up that information from instance metadata service.
Also, got rid of the check where the plugin makes sure that the eni id
and the mac address match by looking up instance metadata. This leads to
addtional delays starting the plugin while adding very little value to
the functionality. Hence, the ENI plugin doesn't do that check anymore.
It's left to the caller instead should make sure that correct values
are passed to the plugin, which the ECS …
=> eni: add ipv4 subnet gateway from config

Makefile, plugins/ecs-bridge/commands/commands.go, plugins/ecs-bridge/engine/engine.go, plugins/ecs-bridge/engine/engine_integ_test.go, plugins/ecs-bridge/engine/engine_test.go
Due to the fact that multiple tasks may be modifying the bridge at the same time, there are race conditions when creating/configuring the bridge, which cause the following error:
```
unable to configure pause container namespace: cni setup: invoke bridge plugin failed: bridge create: unable to add bridge interface ecs-bridge: file exists
unable to configure pause container namespace: cni setup: invoke bridge plugin failed: bridge configure: unable to assign ip address to bridge ecs-bridge: file exists
```
This PR fixes the two race conditions.
When creating the bridge, check whether the bridge exists after failing to create it.
When assigning ip address to the bridge, check whether the ip address is already assigned after failing to assign it.
Unit tests added. Following targets passed: …
=> Fix race condition when create/configure the bridge

CHANGELOG.md, pkg/netlinkwrapper/mocks/netlinkwrapper_mocks.go, pkg/netlinkwrapper/netlink.go, plugins/eni/commands/commands.go, plugins/eni/commands/commands_test.go, plugins/eni/e2eTests/e2e_test.go, plugins/eni/engine/engine.go, plugins/eni/engine/engine_test.go, plugins/eni/engine/mocks/engine_mocks.go, plugins/eni/engine/nsclosure.go, plugins/eni/types/types.go
Add option to set the eni MTU 
```
make unit-test
integration-test
sudo-integration-test
e2e-test
```
New tests cover the changes: 
yes
* Enhancement - Add `MTU` config to ENI plugin
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
yes
=> Add option to set interface MTU in eni plugin

plugins/eni/commands/commands.go, plugins/eni/commands/commands_test.go, plugins/eni/e2eTests/e2e_test.go, plugins/eni/engine/engine.go, plugins/eni/engine/engine_test.go, plugins/eni/engine/mocks/engine_mocks.go, plugins/eni/engine/nsclosure.go, plugins/eni/types/types.go, plugins/eni/types/types_test.go
This PR updates ecs-eni plugin to support assigning multiple IP addresses and gateways per container network interface. The addresses and gateways can be any combination of IPv4 and IPv6 addresses.
Design and implementation details are as discussed in the design meeting.
All unit, integration and e2e tests are updated and pass.
New tests cover the changes: 
Yes. Unit tests are updated to cover the new functionality. I wanted to add IPv6 addresses to the end-to-end test, however that requires updating the vendored AWS SDK as the current version does not support IPv6.
Feature - Support multiple IP (v4 and v6) addresses per interface
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
=> ecs-eni: Support multiple IP (v4 and v6) addresses per interface

plugins/ecs-bridge/commands/commands.go
Previously to this change we would skip running DeleteVeth on cleanup if
cni plugins was not provided with an IPAM config to delete.
The agent codebase, however, does not always pass in an IPAM config on
purpose, when it is only cleaning up a single task, see `includeIPAMConfig` bool in 
https://github.com/aws/amazon-ecs-agent/blame/71a0f6765cc469913a0b09728196feb0d0d33e37/agent/engine/docker_task_engine.go#L1779
and https://github.com/aws/amazon-ecs-agent/blame/71a0f6765cc469913a0b09728196feb0d0d33e37/agent/engine/docker_task_engine.go#L1760
With this change, when we skip the IPAM delete, we no longer immediately
return from the del function. Instead we let the code fall through to
the engine.DeleteVeth call to make sure that veth interfaces are always
cleaned up when a task is being …
=> Always run DeleteVeth on cleanup

Makefile
Make release is failing on [amazon-ecs-agent](https://github.com/aws/amazon-ecs-agent) when we update the submodules.
The Error message is:
```
GOOS=linux CGO_ENABLED=0 go build -installsuffix cgo -a -ldflags "\
-X github.com/aws/amazon-ecs-cni-plugins/pkg/version.GitShortHash=a04bd6ec \
-X github.com/aws/amazon-ecs-cni-plugins/pkg/version.GitPorcelain=0 \
-X github.com/aws/amazon-ecs-cni-plugins/pkg/version.Version=2020.09.0 -s" \
-o /go/src/github.com/aws/amazon-ecs-cni-plugins/bin/plugins/ecs-eni github.com/aws/amazon-ecs-cni-plugins/plugins/eni
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
make: *** [Makefile:40: bin/plugins/ecs-eni] Error 1
make: *** [build-ecs-cni-plugins] Error 2
```
This change is to include `-buildvcs=false` flag to the …
=> Add -buildvcs=false to Makefile

plugins/ecs-bridge/commands/commands_test.go, plugins/eni/engine/engine_test.go, plugins/eni/engine/nsclosure.go
When the CNI plugins in this repo were implemented, IMDS was accessible only over IPv4. EC2 networking team
introduced IMDS access over IPv6 last year. This change extends the BlockIMDS functionality to cover IPV6.
Add a route to black-hole IMDS traffic for IPv6 endpoint.
`GO111MODULE=auto make unit-test`
New tests cover the changes:  updated unit test
Block IMDS access over IPv6 when BlockIMDS is set
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
=> Block IMDS access over IPv6 when BlockIMDS is set

pkg/netlinkwrapper/netlink.go, plugins/ecs-bridge/engine/engine.go
The ecs-bridge bridge currently is created without setting a static MAC address. This means that the bridge MAC address inherits the 'lowest' MAC address of all of it's connected veth interfaces.
What this means for ECS tasks using awsvpc networking mode is that the MAC address of ecs-bridge can be changing as tasks are killed an added to an instance (on the ec2 launch type).
This presents a race condition where some tasks might have an arpcache entry pointing to the old MAC address when a task is killed and the ecs-bridge MAC changes. In rare cases this can lead to brief periods of lost network connectivity within the local network on the host (such as requests to the ECS Task Metadata Endpoint or the ECS credentials endpoint).
By setting a static MAC address at creation we disable this …
=> Set static MAC address when creating ecs-bridge bridge

plugins/ecs-bridge/engine/engine.go
Adds a comment explaining why ecs-bridge needs a static MAC address.
Just a comment.
New tests cover the changes: 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
=> Add comment explaining why ecs-bridge needs a static MAC address
